/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionRouteImport } from './routes/version'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as BuildRouteImport } from './routes/build'
import { Route as IndexRouteImport } from './routes/index'

const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/diagnostic': typeof DiagnosticRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
  '/projects': typeof ProjectsRoute
  '/publish': typeof PublishRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/version': typeof VersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/diagnostic': typeof DiagnosticRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
  '/projects': typeof ProjectsRoute
  '/publish': typeof PublishRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/version': typeof VersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/diagnostic': typeof DiagnosticRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
  '/projects': typeof ProjectsRoute
  '/publish': typeof PublishRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/version': typeof VersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/diagnostic'
    | '/history'
    | '/journal'
    | '/projects'
    | '/publish'
    | '/settings'
    | '/setup'
    | '/version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/diagnostic'
    | '/history'
    | '/journal'
    | '/projects'
    | '/publish'
    | '/settings'
    | '/setup'
    | '/version'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/diagnostic'
    | '/history'
    | '/journal'
    | '/projects'
    | '/publish'
    | '/settings'
    | '/setup'
    | '/version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  DiagnosticRoute: typeof DiagnosticRoute
  HistoryRoute: typeof HistoryRoute
  JournalRoute: typeof JournalRoute
  ProjectsRoute: typeof ProjectsRoute
  PublishRoute: typeof PublishRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  VersionRoute: typeof VersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  DiagnosticRoute: DiagnosticRoute,
  HistoryRoute: HistoryRoute,
  JournalRoute: JournalRoute,
  ProjectsRoute: ProjectsRoute,
  PublishRoute: PublishRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  VersionRoute: VersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
